apiVersion: v1
kind: PersistentVolume
metadata:
  name: wordpresspv
  namespace: test
  labels:
    app: wordpresspv
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 5Gi
  hostPath:
    path: /data/wordpress/
