apiVersion: v1
kind: ServiceAccount
metadata:
  name: test-account
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: read-and-list
  namespace: default
rules:
  - apiGroups: [""]
    resources: ["*"]
    verbs: ["get", "list"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: test-role-binding
  namespace: default
subjects:
  - kind: ServiceAccount
    name: test-account
    namespace: default
    apiGroup: ""
roleRef:
  kind: ClusterRole
  name: read-and-list
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: Pod
metadata:
  name: service-account-test-pod
  namespace: default
spec:
  serviceAccountName: test-account
  containers:
    - name: test-pod
      image: ozgurozturknet/k8s:latest
      ports:
        - containerPort: 80
