apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  namespace: test
spec:
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
        - name: wordpresscon
          image: wordpress
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: "/var/www/html"
              name: wordpressvol
      volumes:
        - name: wordpressvol
          persistentVolumeClaim:
            claimName: wordpresspvc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  namespace: production
spec:
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
        - name: wordpresscon
          image: wordpress
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: "/var/www/html"
              name: wordpressvol
      volumes:
        - name: wordpressvol
          persistentVolumeClaim:
            claimName: wordpresspvc
